# Generated by Django 3.0.2 on 2020-02-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
