# Generated by Django 2.2 on 2020-02-04 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200204_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
