# Generated by Django 2.2 on 2020-02-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200204_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_show',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Show'),
        ),
    ]
