# Generated by Django 3.0.2 on 2020-02-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('feedback', '0004_auto_20200207_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
