# Generated by Django 3.0.1 on 2020-01-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='shows_image',
            field=models.FileField(default=1, upload_to='shows/'),
            preserve_default=False,
        ),
    ]
