# Generated by Django 2.2 on 2020-02-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200208_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='show',
            new_name='shows',
        ),
    ]
