# Generated by Django 3.0.2 on 2020-01-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_show_shows_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='shows_type',
            field=models.CharField(choices=[('TV Show', 'TV Show'), ('Movies', 'Movies')], max_length=20),
        ),
    ]
