# Generated by Django 2.2 on 2020-02-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_favorite_favourite_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favourite_owner',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Show'),
        ),
    ]
