# Generated by Django 2.2 on 2020-02-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200209_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='fav_status',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
