# Generated by Django 2.2 on 2020-02-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200205_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Show'),
        ),
    ]
