# Generated by Django 3.0.2 on 2020-01-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200125_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='shows_genre',
            field=models.CharField(choices=[('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='shows_type',
            field=models.CharField(choices=[('TV Show', 'TV Show'), ('Movie', 'Movie')], max_length=20),
        ),
    ]
