# Generated by Django 3.0.2 on 2020-01-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200125_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='shows_description',
            new_name='shows_Description',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='shows_image',
            new_name='shows_Image',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='shows_name',
            new_name='shows_Name',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='shows_type',
            new_name='shows_Type',
        ),
        migrations.RemoveField(
            model_name='show',
            name='shows_genre',
        ),
        migrations.AddField(
            model_name='show',
            name='shows_Genre',
            field=models.CharField(choices=[('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Thriller', 'Thriller')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
