# Generated by Django 2.2 on 2020-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200205_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_Name', models.CharField(max_length=40)),
                ('r_Email', models.CharField(max_length=40)),
            ],
        ),
    ]
